-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('message_pb')


local PLAYERJOIN = protobuf.Descriptor();
local PLAYERJOIN_PLAYER_ID_FIELD = protobuf.FieldDescriptor();
local PLAYERLEAVE = protobuf.Descriptor();
local PLAYERLEAVE_PLAYER_ID_FIELD = protobuf.FieldDescriptor();
local PLAYERMOVE = protobuf.Descriptor();
local PLAYERMOVE_PLAYER_ID_FIELD = protobuf.FieldDescriptor();
local PLAYERMOVE_X_FIELD = protobuf.FieldDescriptor();
local PLAYERMOVE_Y_FIELD = protobuf.FieldDescriptor();
local PLAYERMOVE_Z_FIELD = protobuf.FieldDescriptor();
local SERVERBROADCAST = protobuf.Descriptor();
local SERVERBROADCAST_PLAYERS_FIELD = protobuf.FieldDescriptor();

PLAYERJOIN_PLAYER_ID_FIELD.name = "player_id"
PLAYERJOIN_PLAYER_ID_FIELD.full_name = ".PlayerJoin.player_id"
PLAYERJOIN_PLAYER_ID_FIELD.number = 1
PLAYERJOIN_PLAYER_ID_FIELD.index = 0
PLAYERJOIN_PLAYER_ID_FIELD.label = 1
PLAYERJOIN_PLAYER_ID_FIELD.has_default_value = false
PLAYERJOIN_PLAYER_ID_FIELD.default_value = ""
PLAYERJOIN_PLAYER_ID_FIELD.type = 9
PLAYERJOIN_PLAYER_ID_FIELD.cpp_type = 9

PLAYERJOIN.name = "PlayerJoin"
PLAYERJOIN.full_name = ".PlayerJoin"
PLAYERJOIN.nested_types = {}
PLAYERJOIN.enum_types = {}
PLAYERJOIN.fields = {PLAYERJOIN_PLAYER_ID_FIELD}
PLAYERJOIN.is_extendable = false
PLAYERJOIN.extensions = {}
PLAYERLEAVE_PLAYER_ID_FIELD.name = "player_id"
PLAYERLEAVE_PLAYER_ID_FIELD.full_name = ".PlayerLeave.player_id"
PLAYERLEAVE_PLAYER_ID_FIELD.number = 1
PLAYERLEAVE_PLAYER_ID_FIELD.index = 0
PLAYERLEAVE_PLAYER_ID_FIELD.label = 1
PLAYERLEAVE_PLAYER_ID_FIELD.has_default_value = false
PLAYERLEAVE_PLAYER_ID_FIELD.default_value = ""
PLAYERLEAVE_PLAYER_ID_FIELD.type = 9
PLAYERLEAVE_PLAYER_ID_FIELD.cpp_type = 9

PLAYERLEAVE.name = "PlayerLeave"
PLAYERLEAVE.full_name = ".PlayerLeave"
PLAYERLEAVE.nested_types = {}
PLAYERLEAVE.enum_types = {}
PLAYERLEAVE.fields = {PLAYERLEAVE_PLAYER_ID_FIELD}
PLAYERLEAVE.is_extendable = false
PLAYERLEAVE.extensions = {}
PLAYERMOVE_PLAYER_ID_FIELD.name = "player_id"
PLAYERMOVE_PLAYER_ID_FIELD.full_name = ".PlayerMove.player_id"
PLAYERMOVE_PLAYER_ID_FIELD.number = 1
PLAYERMOVE_PLAYER_ID_FIELD.index = 0
PLAYERMOVE_PLAYER_ID_FIELD.label = 1
PLAYERMOVE_PLAYER_ID_FIELD.has_default_value = false
PLAYERMOVE_PLAYER_ID_FIELD.default_value = ""
PLAYERMOVE_PLAYER_ID_FIELD.type = 9
PLAYERMOVE_PLAYER_ID_FIELD.cpp_type = 9

PLAYERMOVE_X_FIELD.name = "x"
PLAYERMOVE_X_FIELD.full_name = ".PlayerMove.x"
PLAYERMOVE_X_FIELD.number = 2
PLAYERMOVE_X_FIELD.index = 1
PLAYERMOVE_X_FIELD.label = 1
PLAYERMOVE_X_FIELD.has_default_value = false
PLAYERMOVE_X_FIELD.default_value = 0.0
PLAYERMOVE_X_FIELD.type = 2
PLAYERMOVE_X_FIELD.cpp_type = 6

PLAYERMOVE_Y_FIELD.name = "y"
PLAYERMOVE_Y_FIELD.full_name = ".PlayerMove.y"
PLAYERMOVE_Y_FIELD.number = 3
PLAYERMOVE_Y_FIELD.index = 2
PLAYERMOVE_Y_FIELD.label = 1
PLAYERMOVE_Y_FIELD.has_default_value = false
PLAYERMOVE_Y_FIELD.default_value = 0.0
PLAYERMOVE_Y_FIELD.type = 2
PLAYERMOVE_Y_FIELD.cpp_type = 6

PLAYERMOVE_Z_FIELD.name = "z"
PLAYERMOVE_Z_FIELD.full_name = ".PlayerMove.z"
PLAYERMOVE_Z_FIELD.number = 4
PLAYERMOVE_Z_FIELD.index = 3
PLAYERMOVE_Z_FIELD.label = 1
PLAYERMOVE_Z_FIELD.has_default_value = false
PLAYERMOVE_Z_FIELD.default_value = 0.0
PLAYERMOVE_Z_FIELD.type = 2
PLAYERMOVE_Z_FIELD.cpp_type = 6

PLAYERMOVE.name = "PlayerMove"
PLAYERMOVE.full_name = ".PlayerMove"
PLAYERMOVE.nested_types = {}
PLAYERMOVE.enum_types = {}
PLAYERMOVE.fields = {PLAYERMOVE_PLAYER_ID_FIELD, PLAYERMOVE_X_FIELD, PLAYERMOVE_Y_FIELD, PLAYERMOVE_Z_FIELD}
PLAYERMOVE.is_extendable = false
PLAYERMOVE.extensions = {}
SERVERBROADCAST_PLAYERS_FIELD.name = "players"
SERVERBROADCAST_PLAYERS_FIELD.full_name = ".ServerBroadcast.players"
SERVERBROADCAST_PLAYERS_FIELD.number = 1
SERVERBROADCAST_PLAYERS_FIELD.index = 0
SERVERBROADCAST_PLAYERS_FIELD.label = 3
SERVERBROADCAST_PLAYERS_FIELD.has_default_value = false
SERVERBROADCAST_PLAYERS_FIELD.default_value = {}
SERVERBROADCAST_PLAYERS_FIELD.message_type = PLAYERMOVE
SERVERBROADCAST_PLAYERS_FIELD.type = 11
SERVERBROADCAST_PLAYERS_FIELD.cpp_type = 10

SERVERBROADCAST.name = "ServerBroadcast"
SERVERBROADCAST.full_name = ".ServerBroadcast"
SERVERBROADCAST.nested_types = {}
SERVERBROADCAST.enum_types = {}
SERVERBROADCAST.fields = {SERVERBROADCAST_PLAYERS_FIELD}
SERVERBROADCAST.is_extendable = false
SERVERBROADCAST.extensions = {}

PlayerJoin = protobuf.Message(PLAYERJOIN)
PlayerLeave = protobuf.Message(PLAYERLEAVE)
PlayerMove = protobuf.Message(PLAYERMOVE)
ServerBroadcast = protobuf.Message(SERVERBROADCAST)

